/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_nativeapp_NativeMsg */

#ifndef _Included_com_example_nativeapp_NativeMsg
#define _Included_com_example_nativeapp_NativeMsg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_nativeapp_NativeMsg
 * Method:    getMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_nativeapp_NativeMsg_getMsg
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
